### ISSUE TITLE
Username and device names

### ISSUE THREAD

**Issue by jpmens** [owntracks/traction#4]
Ben says: 
> any reason you capitalise the device name in traction - I am seeing `Ipad` in the device list when I entered it as `ipad` - might lead to confusion?

**Comment by binarybucks** [comment]
Old css entry. Will be removed.

On Mon, Apr 20, 2015 at 11:43 PM, JP Mens <notifications@github.com> wrote:

> Ben says:
>
> any reason you capitalise the device name in traction - I am seeing Ipad
> in the device list when I entered it as ipad - might lead to confusion?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/owntracks/traction/issues/4>.
>



-- 
Mit freundlichen Grüßen / With kind regards
Alexander Rust
